config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  root to: "main#index"

  get '/about_us', to: 'main#about_us'

  get '/properties/filter', to: 'properties#filter'

  post '/mailer/contact', to: 'mailer#contact'
  
  resources :properties
  resources :addresses
  resources :property_features
  resources :amenities
  resources :property_images
end

app/models/amenity.rb
class Amenity < ApplicationRecord
  belongs_to :property
end

app/controllers/amenities_controller.rb
class AmenitiesController < ApplicationController
  before_action :set_amenity, only: %i[ show destroy ]
  before_action :authenticate_user!, only: %i[ edit update destroy ]

  # GET /amenities or /amenities.json
  def index
    @amenities = Amenity.all
  end

  # GET /amenities/1 or /amenities/1.json
  def show
  end

  # GET /amenities/new
  def new
    @amenity = Amenity.new
    @amenity.property_id = params['property_id']
  end

  # GET /amenities/1/edit
  def edit
    @amenity = Amenity.find_by(property_id: params["property_id"])
  end

  # POST /amenities or /amenities.json
  def create
    @amenity = Amenity.new(amenity_params)

    respond_to do |format|
      if @amenity.save
        format.html { redirect_to new_property_image_path(property_id: @amenity.property_id), notice: "Amenity was successfully created." }
        format.json { render :show, status: :created, location: @amenity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @amenity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /amenities/1 or /amenities/1.json
  def update
    @amenity = Amenity.find_by(property_id: params.require(:amenity)["property_id"])
    respond_to do |format|
      if @amenity.update(amenity_params)
        format.html { redirect_to edit_property_image_path(property_id: @amenity.property_id), notice: "Amenity was successfully updated." }
        format.json { render :show, status: :ok, location: @amenity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @amenity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amenities/1 or /amenities/1.json
  def destroy
    @amenity.destroy
    respond_to do |format|
      format.html { redirect_to amenities_url, notice: "Amenity was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amenity
      @amenity = Amenity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def amenity_params
      params.require(:amenity).permit(:bbq, :sport_zones, :gym, :pool, :comunal_room, :property_id)
    end
end

app/helpers/amenities_helper.rb
module AmenitiesHelper
end

app/views/amenities/_form.html.erb
<%= form_with(model: amenity) do |form| %>
  <% if amenity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(amenity.errors.count, "error") %> prohibited this amenity from being saved:</h2>

      <ul>
        <% amenity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bbq %>
    <%= form.check_box :bbq %>
  </div>

  <div class="field">
    <%= form.label :sport_zones %>
    <%= form.check_box :sport_zones %>
  </div>

  <div class="field">
    <%= form.label :gym %>
    <%= form.check_box :gym %>
  </div>

  <div class="field">
    <%= form.label :pool %>
    <%= form.check_box :pool %>
  </div>

  <div class="field">
    <%= form.label :comunal_room %>
    <%= form.check_box :comunal_room %>
  </div>

  <div class="field">
    <%= form.label :property_id %>
    <%= form.text_field :property_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/amenities/edit.html.erb
<h1>Editing Amenity</h1>

<%= render 'form', amenity: @amenity %>

<%= link_to 'Show', property_path(@amenity.property_id) %> |
<%= link_to 'Back', properties_path %>

app/views/amenities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Amenities</h1>

<table>
  <thead>
    <tr>
      <th>Bbq</th>
      <th>Sport zones</th>
      <th>Gym</th>
      <th>Pool</th>
      <th>Comunal room</th>
      <th>Property</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @amenities.each do |amenity| %>
      <tr>
        <td><%= amenity.bbq %></td>
        <td><%= amenity.sport_zones %></td>
        <td><%= amenity.gym %></td>
        <td><%= amenity.pool %></td>
        <td><%= amenity.comunal_room %></td>
        <td><%= amenity.property_id %></td>
        <td><%= link_to 'Show', amenity %></td>
        <td><%= link_to 'Edit', edit_amenity_path(amenity) %></td>
        <td><%= link_to 'Destroy', amenity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Amenity', new_amenity_path %>

app/views/amenities/new.html.erb
<h1>New Amenity</h1>

<%= render 'form', amenity: @amenity %>

<%= link_to 'Back', amenities_path %>

app/views/amenities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bbq:</strong>
  <%= @amenity.bbq %>
</p>

<p>
  <strong>Sport zones:</strong>
  <%= @amenity.sport_zones %>
</p>

<p>
  <strong>Gym:</strong>
  <%= @amenity.gym %>
</p>

<p>
  <strong>Pool:</strong>
  <%= @amenity.pool %>
</p>

<p>
  <strong>Comunal room:</strong>
  <%= @amenity.comunal_room %>
</p>

<p>
  <strong>Property:</strong>
  <%= @amenity.property_id %>
</p>
<% if admin_signed_in? %>
  <%= link_to 'Edit', edit_amenity_path(@amenity) %> |
<% end %>
<%= link_to 'Back', amenities_path %>