config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  root to: "main#index"

  get '/about_us', to: 'main#about_us'

  get '/properties/filter', to: 'properties#filter'

  post '/mailer/contact', to: 'mailer#contact'
  
  resources :properties
  resources :addresses
  resources :property_features
  resources :amenities
  resources :property_images
end

app/models/property.rb
class Property < ApplicationRecord
    belongs_to :user
    has_one :address, dependent: :destroy
    has_one :property_feature, dependent: :destroy
    has_one :amenity, dependent: :destroy
    has_one :property_image, dependent: :destroy

  def self.search_by(params)
    columns = self.columns_builder(params)
    others_conditions = self.greater_less_conditions(params)
    properties = Property.joins(:property_feature, :amenity, :address).where(columns)
    
    others_conditions.reject { |c| c.empty? }.each do |condition|
      properties = properties.and(Property.joins(:property_feature, :amenity, :address).where(condition))
    end
    properties
  end

  private

  def self.columns_builder(params)
    property_feature = self.build_property_feature_filter(params)
    amenity = self.build_amenity_filter(params)
    address = self.build_address_filter(params)
    columns = %i[kind operation].each_with_object({}) do |key, hsh| 
      next if params[key].nil?
      hsh[key] = params[key].to_s 
    end
    columns[:property_feature] = property_feature if property_feature.present?
    columns[:amenity] = amenity if amenity.present?
    columns[:address] = address if address.present?

    columns
  end

  def self.build_property_feature_filter(params)
    %i[year_old rooms bathrooms parking trunk].each_with_object({}) do |key, hsh|

      if key == :rooms
        self.fill_checkbox_options(hsh, key, params, %i[one_room two_rooms three_rooms four_rooms])
      end
      if key == :bathrooms
        self.fill_checkbox_options(hsh, key, params, %i[one_bathroom two_bathrooms three_bathrooms])
      end
      if key == :parking
        self.fill_checkbox_options(hsh, key, params, %i[one_parking two_parking three_parking])
      end
      if key == :trunk
        self.fill_checkbox_options(hsh, key, params, %i[one_trunk two_trunk])
      end
      
      next if params[key].nil?
      hsh[key] = params[key].to_i
    end
  end

  def self.build_amenity_filter(params)
    %i[bbq sport_zones gym pool].each_with_object({}) do |key, hsh|
        next if params[key].nil? || params[key] == '0'
        hsh[key] = ActiveModel::Type::Boolean.new.cast(params[key])
    end
  end

  def self.build_address_filter(params)
    %i[province city municipality neighborhood main_street].each_with_object({}) do |key, hsh|
        next if params[key].nil?
        hsh[key] = params[key].to_s.downcase
    end
  end

  def self.array_of_values(keys, params)
    values = []
    keys.each_with_index {|key, index| values.push(index + 1) if params[key] == '1' } 
    values
  end

  def self.greater_less_conditions(params)
    from_price = params[:from_price].nil? ? [] : ["price >= ?", params[:from_price].to_i]
    to_price = params[:to_price].nil? ? [] : ["price <= ?", params[:to_price].to_i]
    from_total_area = params[:from_total_area].nil? ? [] : ["property_feature.total_area >= ?", params[:from_total_area].to_f]
    to_total_area = params[:to_total_area].nil? ? [] : ["property_feature.total_area <= ?", params[:to_total_area].to_f]

    [
      from_price, 
      to_price, 
      from_total_area, 
      to_total_area, 
    ]
  end

  def self.fill_checkbox_options(hsh, key, params, fields)
    values = self.array_of_values(fields, params)
    hsh[key] = values if values != []  
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ edit update destroy ]
  before_action :filter_params, only: %i[ filter ]

  # GET /properties or /properties.json
  def index
    @properties = Property.all.includes([:address, :amenity, :property_feature, :property_image]).page(params[:page])
  end

  # GET /properties/1 or /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties or /properties.json
  def create
    @property = Property.new(property_params)
    @property.user_id = current_user.id
    respond_to do |format|
      if @property.save
        format.html { redirect_to new_property_feature_path(property_id: @property.id), notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to edit_property_feature_path(property_id: @property.id), notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def filter
    @properties = Property.search_by(filter_params).page(params[:page])
    respond_to do |format|
      format.html { render :index }
      format.json { render :index, location: @properties }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:name, :description, :price, :currency, :kind, :operation, :page)
    end

    def filter_params
      params_permited = %i[
        province city municipality neighborhood from_total_area to_total_area year_old one_room
        two_rooms three_rooms four_rooms one_bathroom two_bathrooms three_bathrooms one_parking two_parking
        three_parking one_trunk two_trunk bbq sport_zones gym pool
        from_price to_price kind operation main_street page
      ]
      params.permit(params_permited).reject{|_, param| param.blank?}
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
  def price_formated(property)
    "#{number_with_precision(property.price, :precision => 0, :delimiter => ',')} #{property.currency.upcase}"
  end

  # Enums

  def neighboords    
    {
       caba: [
         ['Seleccione', nil],
         ['Agronomía', 'agronomia'],
         ['Almagro', 'almagro'],
         ['Balvanera', 'balvanera'],
         ['Barracas', 'barracas'],
         ['Belgrano', 'belgrano'],
         ['Boedo', 'boedo'],
         ['Caballito', 'caballito'],
         ['Chacarita', 'chacarita'],
         ['Coghlan', 'coghlan'],
         ['Colegiales', 'colegiales'],
         ['Constitución', 'constitucion'],
         ['Flores', 'flores'],
         ['Floresta', 'floresta'],
         ['La Boca', 'la boca'],
         ['La Paternal', 'la paternal'],
         ['Liniers', 'liniers'],
         ['Mataderos', 'mataderos'],
         ['Monte Castro', 'monte castro'],
         ['Montserrat', 'montserrat'],
         ['Nueva Pompeya', 'nueva pompeya'],
         ['Nuñez', 'nuñez'],
         ['Palermo', 'palermo'],
         ['Parque Avellaneda', 'parque avellaneda'],
         ['Parque Chacabuco', 'parque chacabuco'],
         ['Parque Chas', 'parque chas'],
         ['Parque Patricios', 'parque patricios'],
         ['Puerto Madero', 'puerto madero'],
         ['Recoleta', 'recoleta'],
         ['Retiro', 'retiro'],
         ['Saavedra', 'saavedra'],
         ['San Cristóbal', 'san cristobal'],
         ['San Nicolás', 'san nicolas'],
         ['San Telmo', 'san telmo'],
         ['Versalles', 'versalles'],
         ['Villa Crespo', 'villa crespo'],
         ['Villa Devoto', 'villa devoto'],
         ['Villa General Mitre', 'villa general mitre'],
         ['Villa Lugano', 'villa lugano'],
         ['Villa Luro', 'villa luro'],
         ['Villa Ortúzar', 'villa ortuzar'],
         ['Villa Pueyrredón', 'villa pueyrredón'],
         ['Villa Real', 'villa Real'],
         ['Villa Riachuelo', 'villa riachuelo'],
         ['Villa Santa Rita', 'villa santa rita'],
         ['Villa Soldati', 'villa soldati'],
         ['Villa Urquiza', 'villa urquiza'],
         ['Villa del Parque', 'villa del parque'],
         ['Vélez Sarsfield', 'velez sarsfield']
       ]
     }
   end
 
   def provinces
     [
         ['Seleccione', nil],
         ['Buenos Aires', 'buenos aires'],
         ['Caba', 'caba'],
         ['Catamarca', 'catamarca'],
         ['Chaco', 'chaco'],
         ['Chubut', 'chubut'],
         ['Córdoba', 'córdoba'],
         ['Corrientes', 'corrientes'],
         ['Entre Ríos', 'entre rios'],
         ['Formosa', 'formosa'],
         ['Jujuy', 'jujuy'],
         ['La Pampa', 'la pampa'],
         ['La Rioja', 'la rioja'],
         ['Mendoza', 'mendoza'],
         ['Misiones', 'misiones'],
         ['Neuquén', 'neuquen'],
         ['Río Negro', 'rio negro'],
         ['Salta', 'salta'],
         ['San Juan', 'san Juan'],
         ['San Luis', 'san Luis'],
         ['Santa Cruz', 'santa Cruz'],
         ['Santa Fe', 'santa Fe'],
         ['Santiago del Estero', 'santiago del estero'],
         ['Tierra del Fuego, Antártida e Islas del Atlántico Sur', 'tierra del fuego, antártida e islas del atlantico sur'],
         ['Tucumán', 'tucuman']
     ]
   end
 
   def operations
     [
       ['Seleccione', nil],
       ['Venta', 'venta'],
       ['Alquiler', 'alquiler']
     ]
   end
 
   def kind
     [
       ['Seleccione', nil],
       ['Casa', 'casa'], 
       ['Apartamento', 'apartamento'],
       ['Local', 'Local']
       ]
   end
end

app/views/properties/_property_card.html.erb
<%= link_to property_path(property), class: "remove-link-styles col col-12 col-md-4" do %>
  <div class="card card-container">
    <div class="carrousel-index-container">
      <%= render 'properties/carrousel', property: property %>
    </div>
    <div class='card-description-container'>
      <div class="card-icons-container">
        <i class="fa-solid fa-bed"> <%= property.property_feature.rooms%></i> 
        <i class="fa-solid fa-bath"> <%= property.property_feature.bathrooms%></i>
        <i class="fa-solid fa-car"> <%= property.property_feature.parking%></i>
        <i class="fa-solid fa-expand"> <%= property.property_feature.total_area%></i>
      </div>
      <div>
        <p class="card-description"><%= "#{property.name.capitalize} en #{property.operation} en 
                #{property.address.province}, #{property.address.city}, 
                #{property.address.municipality},
                #{property.address.main_street} #{property.address.number}"%></p>
        <h4><%= price_formated(property) %></h4>
      </div>
    </div>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'properties/partials/form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<div class="container-fluid row justify-content-start">
  <%= render 'properties/partials/filter_form'%>
  <div class="col-md-10 properties-container p-3">
    <div class="row justify-content-center">
      <% @properties.each do |property| %>
        <%= render "properties/partials/property_card", property: property%>
      <% end %>
    </div>
  </div>
</div>
<%= paginate @properties %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'properties/partials/form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<div class='container pt-3'>
  <div class='row'>
    <div class='col-12 col-md-9'>
    <%# carrousel container %>
      <div class='col-12 property-sections-carrousel-container'>
        <%= render 'properties/partials/carrousel', property: @property %>
        <div class='property-sections-carrousel-container property-sections-container'>
          <h3><%= price_formated(@property) %></h3>
          <%= render 'property_features/partials/icons_container', property_feature: @property.property_feature %>
          <%# address %>
          <div class='address-property-container'>
            <%= 
              "#{@property.address.main_street.capitalize} #{@property.address.number}, 
               #{@property.address.neighborhood.capitalize}, #{@property.address.city.capitalize}"
            %>
          </div>
        </div>
      </div>

      <%# description %>
      <div class='col-12 property-sections-container'>
        <h5>Descripcion</h5>
        <p>
          <%= @property.description %>
        </p>
      </div>
      <%# caracteristicas %>
      <div class='row col-12 property-sections-container'>
        <%= render 'property_features/partials/features', property_feature: @property.property_feature %>
        <p>
          <h5>Amenities</h5>
          <div class='col-12 col-md-6'><i class='fa-solid fa-bacon'></i> BBQ: <%= @property.amenity.bbq ? 'Si' : 'No' %></div>
          <div class='col-12 col-md-6'><i class='fa-solid fa-futbol'></i> Zona deportiva: <%= @property.amenity.sport_zones ? 'Si' : 'No' %></div>
          <div class='col-12 col-md-6'><i class='fa-solid fa-dumbbell'></i> Gym: <%= @property.amenity.gym ? 'Si' : 'No' %></div>
          <div class='col-12 col-md-6'><i class='fa-solid fa-person-swimming'></i> Piscina: <%= @property.amenity.pool ? 'Si' : 'No' %></div>
          <div class='col-12 col-md-6'><i class='fa-solid fa-people-roof'></i> SUM: <%= @property.amenity.comunal_room ? 'Si' : 'No'%></div>
        </p>
      </div>
      <%# map %>
      <div class='col-12'>
        <iframe width='100%' height='600' frameborder='0' scrolling='no' marginheight='0' marginwidth='0' src='http://maps.google.com/maps/place?output=embed&z=16&t=m&q=loc:<%= @property.address.latitude %>+<%= @property.address.longitude %>'>
        </iframe>
      </div>
    </div>
    <div class='col-12 col-md-3'>
      <%# contact-container %>
      <%= render 'mailer/partials/contact_form', property: @property %>
      <% if admin_signed_in? || @property.user_id == current_user.id %>
        <%= link_to 'Editar Propiedad', edit_property_path(@property), class: 'nav-link font-w-500' %>
      <% end %>
    </div>    
  </div>
</div>