config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  root to: "main#index"

  get '/about_us', to: 'main#about_us'

  get '/properties/filter', to: 'properties#filter'

  post '/mailer/contact', to: 'mailer#contact'
  
  resources :properties
  resources :addresses
  resources :property_features
  resources :amenities
  resources :property_images
end

app/models/property_feature.rb
class PropertyFeature < ApplicationRecord
  belongs_to :property
end

app/controllers/property_features_controller.rb
class PropertyFeaturesController < ApplicationController
  before_action :set_property_feature, only: %i[ show destroy ]
  before_action :authenticate_user!, only: %i[ edit update destroy ]

  # GET /property_features or /property_features.json
  def index
    @property_features = PropertyFeature.all
  end

  # GET /property_features/1 or /property_features/1.json
  def show
  end

  # GET /property_features/new
  def new
    @property_feature = PropertyFeature.new
    @property_feature.property_id = params['property_id']
  end

  # GET /property_features/1/edit
  def edit
    @property_feature = PropertyFeature.find_by(property_id: params["property_id"])
  end

  # POST /property_features or /property_features.json
  def create
    @property_feature = PropertyFeature.new(property_feature_params)

    respond_to do |format|
      if @property_feature.save
        format.html { redirect_to new_address_path(property_id: @property_feature.property_id), notice: "Property feature was successfully created." }
        format.json { render :show, status: :created, location: @property_feature }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property_feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /property_features/1 or /property_features/1.json
  def update
    @property_feature = PropertyFeature.find_by(property_id: params.require(:property_feature)["property_id"])
    respond_to do |format|
      if @property_feature.update(property_feature_params)
        format.html { redirect_to edit_address_path(property_id: @property_feature.property_id), notice: "Property feature was successfully updated." }
        format.json { render :show, status: :ok, location: @property_feature }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property_feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /property_features/1 or /property_features/1.json
  def destroy
    @property_feature.destroy
    respond_to do |format|
      format.html { redirect_to property_features_url, notice: "Property feature was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property_feature
      @property_feature = PropertyFeature.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_feature_params
      params.require(:property_feature).permit(:total_area, :build_area, :year_old, :rooms, :bathrooms, :social_bathrooms, :parking, :trunk, :property_id)
    end
end

app/helpers/property_features_helper.rb
module PropertyFeaturesHelper
end

app/views/property_features/edit.html.erb
<h1>Editing Property Feature</h1>

<%= render 'property_features/partials/form', property_feature: @property_feature %>

<%= link_to 'Show', property_path(@property_feature.property_id) %> |
<%= link_to 'Back', properties_path %>

app/views/property_features/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Property Features</h1>

<table>
  <thead>
    <tr>
      <th>Total area</th>
      <th>Build area</th>
      <th>Year old</th>
      <th>Rooms</th>
      <th>Bathrooms</th>
      <th>Social bathrooms</th>
      <th>Parking</th>
      <th>Trunk</th>
      <th>Property</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @property_features.each do |property_feature| %>
      <tr>
        <td><%= property_feature.total_area %></td>
        <td><%= property_feature.build_area %></td>
        <td><%= property_feature.year_old %></td>
        <td><%= property_feature.rooms %></td>
        <td><%= property_feature.bathrooms %></td>
        <td><%= property_feature.social_bathrooms %></td>
        <td><%= property_feature.parking %></td>
        <td><%= property_feature.trunk %></td>
        <td><%= property_feature.property_id %></td>
        <td><%= link_to 'Show', property_feature %></td>
        <td><%= link_to 'Edit', edit_property_feature_path(property_feature) %></td>
        <td><%= link_to 'Destroy', property_feature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property Feature', new_property_feature_path %>

app/views/property_features/new.html.erb
<h1>New Property Feature</h1>

<%= render 'property_features/partials/form', property_feature: @property_feature %>

<%= link_to 'Back', property_features_path %>

app/views/property_features/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Total area:</strong>
  <%= @property_feature.total_area %>
</p>

<p>
  <strong>Build area:</strong>
  <%= @property_feature.build_area %>
</p>

<p>
  <strong>Year old:</strong>
  <%= @property_feature.year_old %>
</p>

<p>
  <strong>Rooms:</strong>
  <%= @property_feature.rooms %>
</p>

<p>
  <strong>Bathrooms:</strong>
  <%= @property_feature.bathrooms %>
</p>

<p>
  <strong>Social bathrooms:</strong>
  <%= @property_feature.social_bathrooms %>
</p>

<p>
  <strong>Parking:</strong>
  <%= @property_feature.parking %>
</p>

<p>
  <strong>Trunk:</strong>
  <%= @property_feature.trunk %>
</p>

<p>
  <strong>Property:</strong>
  <%= @property_feature.property_id %>
</p>

<% if admin_signed_in? %>
  <%= link_to 'Edit', edit_property_feature_path(@property_feature) %> |
<% end %>
<%= link_to 'Back', property_features_path %>