config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  root to: "main#index"

  get '/about_us', to: 'main#about_us'

  get '/properties/filter', to: 'properties#filter'

  post '/mailer/contact', to: 'mailer#contact'
  
  resources :properties
  resources :addresses
  resources :property_features
  resources :amenities
  resources :property_images
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: %i[ show destroy ]
  before_action :authenticate_user!, only: %i[ edit update destroy ]
  # GET /addresses or /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1 or /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
    @address.property_id = params['property_id']
  end

  # GET /addresses/1/edit
  def edit
    @address = Address.find_by(property_id: params["property_id"])
  end

  # POST /addresses or /addresses.json
  def create
    @address = Address.new(address_params)
    set_coordinates(@address)
    respond_to do |format|
      if @address.save
        format.html { redirect_to new_amenity_path(property_id: @address.property_id), notice: "Property was successfully created." }
        format.html { redirect_to @address, notice: "Address was successfully created." }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1 or /addresses/1.json
  def update
    @address = Address.find_by(property_id: params.require(:address)["property_id"])
    @address.assign_attributes(address_params)
    set_coordinates(@address)
    respond_to do |format|
      if @address.save
        format.html { redirect_to edit_amenity_path(property_id: @address.property_id), notice: "Address was successfully updated." }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1 or /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: "Address was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def address_params
      params.require(:address).permit(:province, :city, :municipality, :neighborhood, :main_street, :number, :secondary_street, :property_id)
    end

    def set_coordinates(address)
      coordinates   = Geocoder.search(address.full_address).first.coordinates
      address.latitude = coordinates[0]
      address.longitude = coordinates[1]
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.erb
<%= form_with(model: address) do |form| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
        <% address.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :province %>
    <%= form.text_field :province %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :municipality %>
    <%= form.select :municipality, options_for_select(neighboords[:caba]), {}, class: "form-select" %>
  </div>

  <div class="field">
    <%= form.label :neighborhood %>
    <%= form.select :neighborhood, options_for_select(neighboords[:caba]), {}, class: "form-select" %>
  </div>

  <div class="field">
    <%= form.label :main_street %>
    <%= form.text_field :main_street %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :secondary_street %>
    <%= form.text_field :secondary_street %>
  </div>

  <div class="field">
    <%= form.label :property_id %>
    <%= form.text_field :property_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', property_path(@address.property_id) %> |
<%= link_to 'Back', properties_path %>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Province</th>
      <th>City</th>
      <th>Municipality</th>
      <th>Main street</th>
      <th>Secondary street</th>
      <th>Property</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.province %></td>
        <td><%= address.city %></td>
        <td><%= address.municipality %></td>
        <td><%= address.main_street %></td>
        <td><%= address.secondary_street %></td>
        <td><%= address.property_id %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Province:</strong>
  <%= @address.province %>
</p>

<p>
  <strong>City:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>Municipality:</strong>
  <%= @address.municipality %>
</p>

<p>
  <strong>Main street:</strong>
  <%= @address.main_street %>
</p>

<p>
  <strong>Secondary street:</strong>
  <%= @address.secondary_street %>
</p>

<p>
  <strong>Property:</strong>
  <%= @address.property_id %>
</p>
<% if admin_signed_in? %>
  <%= link_to 'Edit', edit_address_path(@address) %> |
<% end %>
<%= link_to 'Back', addresses_path %>